language: node_js
node_js:
  - "node"
  - "lts/*"
before_deploy: "ls -la src && ls -la && npm publish . --dry-run"
deploy:
  provider: npm
  email: $DEPLOY_NPM_EMAIL
  api_key: $DEPLOY_NPM_API_KEY
  skip_cleanup: true
